version: '3.0'

services:
  db:
    container_name: golang-db
    build: 
      context: ./
      dockerfile: db.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASS}"
      MYSQL_DATABASE: "${MYSQL_DB}"
      # MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
    ports:
      - "3305:3306"
  app:
    container_name: golang-app
    build:
      context: ./
      dockerfile: app.Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/src/app
    tty: true
    depends_on:
      - db
  adminer:
    image: adminer:latest
    container_name: golang-adminer
    depends_on:
      - db
    restart: always
    ports:
      - "9090:8080"